# Generated by Django 5.2.17 on 2026-10-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('registered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=24, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_at', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=40)),
                ('payment_attempts', models.PositiveSmallIntegerField(default=1)),
                ('delivery_address', models.CharField(max_length=240)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low risk'), ('medium', 'Medium risk'), ('high', 'High risk')], db_index=True, default='low', max_length=8)),
                ('investigation_status', models.CharField(choices=[('pending', 'Pending review'), ('under_review', 'Under review'), ('reviewed', 'Reviewed')], db_index=True, default='pending', max_length=16)),
                ('ai_explanation', models.TextField(blank=True)),
                ('ai_explanation_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer')),
            ],
            options={
                'ordering': ['-ordered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=2000)),
                ('created_by', models.CharField(default='Reviewer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RiskSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=240)),
                ('points', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='orders.order')),
            ],
            options={
                'ordering': ['-points', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['risk_level', '-ordered_at'], name='orders_orde_risk_le_1f8936_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['investigation_status', '-ordered_at'], name='orders_orde_investi_510c60_idx'),
        ),
        migrations.AddConstraint(
            model_name='risksignal',
            constraint=models.UniqueConstraint(fields=('order', 'code'), name='unique_risk_signal_per_order'),
        ),
    ]
